### PR TITLE
fixed moz thumb

### PR DESCRIPTION
**Pull request by gumillie222**

### CODE REVIEW

**Comment by JamesPHoughton** [comment]
Todo: Set up GH actions to run the tests in both chrome and firefox (and maybe edge?)

**Comment by JamesPHoughton** [comment]
@gumillie222 - tests are failing for me locally and on github - would you mind revisiting this?

**Comment by kepstein23** [comment]
@gumillie222 yes, we can work tomorrow!

**Comment by gumillie222** [comment]
Most of the tests failing are on Firefox and on cypress cloud specifically (all tests ran successfully on local cypress). Kimberly and I worked on this for a while. Here is a particular issue: 

Screenshot 2023-06-29 at 11 33 23 PM
Screenshot 2023-06-29 at 11 32 22 PM

The last test is failing on cypress cloud, issue being `openResponse` not being stored properly. All the ones before passed, including the one testing if the text is being entered into the text box. We suspect that it's an issue with how cypress cloud handles local storage, and it's weird because the other 2 values are being stored and read. We can't find enough helpful resource on this, so @JamesPHoughton, might need your help!

**Comment by kepstein23** [comment]
> Most of the tests failing are on Firefox and on cypress cloud specifically (all tests ran successfully on local cypress). Kimberly and I worked on this for a while. Here is a particular issue:
> 
> Screenshot 2023-06-29 at 11 33 23 PM Screenshot 2023-06-29 at 11 32 22 PM
> The last test is failing on cypress cloud, issue being `openResponse` not being stored properly. All the ones before passed, including the one testing if the text is being entered into the text box. We suspect that it's an issue with how cypress cloud handles local storage, and it's weird because the other 2 values are being stored and read. We can't find enough helpful resource on this, so @JamesPHoughton, might need your help!

Would also like to add that we tried asserting that the textarea's value is updated, which passes locally and in CI, and we tried adding a wait statement which didn't help.  This led us to believe that there's an issue with the text area's value not being saved to localStorage in the cloud.  Also, notably, this is only happening in Firefox on the CI and is not happening in firefox or Electron locally.

**Comment by JamesPHoughton** [comment]
Tests all run successfully on local...

**Review by JamesPHoughton — APPROVED** [review]

**Pull request merged**
